FROM microsoft/iis:10.0.14393.206
SHELL ["powershell"]

RUN Install-WindowsFeature NET-Framework-45-ASPNET ; \
    Install-WindowsFeature Web-Asp-Net45

RUN mkdir C:\\MyWebsite

Copy  . C:\\Mywebsite
RUN Remove-WebSite -Name 'Default Web Site'
RUN New-Website -Name 'MyWebsite' -Port 80 \
    -PhysicalPath 'C:\MyWebsite' -ApplicationPool '.NET v4.5'
EXPOSE 80